name: Build Sample React workflow
on:
  push:
    branches:
      - "*" 
  pull_request:
    types: [opened, reopened, synchronize]
  
  workflow_dispatch:
    inputs: 
      BRANC_NAME:
        description: 'Specify branch name you would like to build'
        required: false
      BUILD_VERSION:
        description: 'Specify version you would like to build or override'
        required: false
      PERFORM_RELEASE:
        description: '[Release] perform release'
        required: false
        
jobs:
  check-permission:
    runs-on: ubuntu-latest
    steps:
      # this action will fail the whole workflow if permission check fails
      - name: check permission
        uses: zowe-actions/shared-actions/permission-check@main
        with:
          user: ${{ github.actor }}
          github-repo: ${{ github.repository }}
          github-user: ${{ secrets.ZOWE_ROBOT_USER }}
          github-passwd: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    needs: check-permission
    steps:
      - name: '[Prep 1] Checkout'
        uses: actions/checkout@v2

      - name: '[Prep 2] Cache node modules'
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ~/.nvm/.cache
            ~/.nvm/versions
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
      
      - name: '[Prep 3] Setup jFrog CLI'
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
          
      - name: '[Prep 4] prepare workflow'
        uses: zowe-actions/zlux-builds/prepare-workflow@users/jstruga/testplugins
        with:
          github-user: ${{ secrets.ZOWE_ROBOT_USER }}
          github-password: ${{ secrets.ZOWE_ROBOT_TOKEN }}
          github-email: ${{ secrets.ZOWE_ROBOT_EMAIL }}
          
     - name: '[Prep 5] build and test plugin'
        uses: zowe-actions/zlux-builds/zlux-plugins@users/jstruga/testplugins
        with:
          build-zss: false
 